# Title, Goal Statement, Conventions
**Title:** Barcat Deals
**Goal Statement:** Our goal for Barcat Deals is to give students an easier way to find deals around campus at the University of Cincinnati. By leveraging AI, we can create an automated process to find deals from various social media accounts from businesses.

**Basic Inputs**: Inputs for our application include social media posts to be processed by an AI. Also manual input from business owners for their own deals.

**Basic Outputs:** Students will be able to retrieve deals from bars and restaurants around campus.

This document will only cover components (insert component here) and (insert component here). The rest of the components in the D0 diagram are deferred to D2.

**Conventions in All Diagrams:**
to be done later
# Data Flow Diagram
[![](https://mermaid.ink/img/pako:eNqtVW1v2jAQ_iuWP20SdFAITfItLZmE1kK1QCdNSNERG7CW2JHtdGXAf58D4aUJWTup-RDFd37unnt856xxJAjFLqayz2AhIZlyZJ5gPOn7wzHabJpNsUaB9-T3w77v3SMXTXHbvIfok4Jnqj5P8R5y6wX-fsubIILghHvyhxP_gDkFOYMshdI1-4PR3cC7Dx_8_sALH0fB-ByX1uNuJ8Fg6AdBOPox9L-fgxLgsDAMZyv0BYnffPd5DHKx1A0KJrcPg_G4XG4bfWIKQZ1EG-RNxqMH75-4Avma76H6y2n3VWQQxyukslnCzlSoClbEqqGSywhSGRUY1-KM0aFD1vtl_igtGV8gRtDjt5N1JkRMgSOjalh8753bY6hTo7wZrbAqnRHKdWi8X6veGSgaEgrxuX9bo-V7Uz5TntGahDQBFpfS7PvtvdFnmWKcKhVySCiquIEQabyohhVEkciMHIN-WdrKcX9EuUpkMqJhGoOeC5nU-QtWFbemL1UjS0yDqJOZgKaaGS3yl9KQpOVjPA7TR5S06xZCVSRZqpngVaUjQ2gh5KoKhZUKgZNwxxRd6Pw4EksRo_LZvJ7emioal9jm95K82NylMf6foPl1WVZnHgvQKBJ8zsy8mTNVkZD0wikZ4SClJDS7C0a4gReSEexqmdEGTqg0Q2KWeMdpivWSJnSK84tGUpK9NAnIX81IxELmt0yOT4H_FCI5hJAiWyyxO4dYmVWW5smLv9ZxC-WEyru87bBrO-1dDOyu8Qt2ratry-7ZnetWt2e17BungVfG6lxZttO97rY7nU6rdWNvG_jPLmnryml12j3HsrtWx7GsXnv7F9I-G0Y?type=png)](https://mermaid.live/edit#pako:eNqtVW1v2jAQ_iuWP3USdLw0AfItLZmE1kK1QCdNSNERG7CW2JHtdKXAf58D4aUJWTup-RDFPj93zz1356xxKAjFDqayz2AhIZ5yZB5_POl7wzHabOp1sUa---T1g77n3iMHTXHTvIfoSsEzVV-meA-5dX1vf-RdEEFwwj15w4l3wJycnEGWQumK8_7obuDeBw9ef-AGjyN_fI5LqnG3E38w9Hw_GP0cej_OQTFwWBiGsxX6isQfvvs8OrmY6gb5k9uHwXhcTLeJrphCUCXRBrmT8ejB_ScuR77le8j-cth9FilE0QqpdBazMxXKguW-KqhkMoJURgXGtThjdOiQ9X6ZPUpLxheIEfT4_bQ7EyKiwJFRNci_98bt0dWpUd71lu8qnRLKdWCs38rWGSgaEArRuX1boeVHQz5TntKKgDQGFhXC7Pvto95nqWKcKhVwiCkqmYEQaayoghWEoUiNHIN-UdpSuT8jXSVSGdIgiUDPhYyr7DmrklnTl_Imi02DqNM2AU01M1pkL6UhToplPA7TZ6S06xZCVShZopngZaVDQ2gh5KoMhZUKgJNgxxRd6PwoFEsRoWJt3k5vRRa1S2yze0lebO7CGP-P0-y6LKozjwRoFAo-Z2beTE1VKCS9UCUjHCSUBOZ0zgjX8EIygh0tU1rDMZVmSMwS7zhNsV7SmE5xdtFIStKXOgH5ux6KSMjslsnwCfBfQsQHF1KkiyV25hAps0qTLHj-1zoeoZxQeZe1HXa6nfbOB3bW-AU7zc51y-ra3VbLavQ6tmW3aniVnbq2ur2bpm012r2G3bK2Nfy6i9q47jXaTbtndW-sds-y7Ob2L-0TG4A)

| Structural Decisions                                                                           | What we chose and why                                                                                                                                                                                                                                                                                                                                   |
| ---------------------------------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| **Relational model (RDBMS) over key-value or document store**                                  | Each entity has a clear relationship with each other, and everyone in our group has experience with using SQL and databases.                                                                                                                                                                                                                            |
| **`VENUE` is its own entity**                                                                  | Venues have independent attributes (address, social media account ID) and host multiple deals and scraped social media posts over time. Moving venue out of a flat deal attribute into its own entity eliminates redundant values across deal rows.                                                                                                     |
| **`SOCIAL_MEDIA_POST` is its own entity**                                                      | Raw post payloads (platform, account, text, images, timestamps) are fetched by the Ingestion Service before parsing. Keeping posts separate from extracted deals preserves raw post history for auditing, scraper tuning, and handling single posts that mention multiple deals.                                                                        |
| **`SAVED_DEAL` is its own entity (many-to-many)**                                              | A student can save many deals, and a deal can be saved by many students. Creating an explicit join table with `student_id` and `base_deal_id` maintains First Normal Form (1NF) and enables fast, indexed lookups of user bookmarks.                                                                                                                    |
| **`BASE_DEAL` split into `SUBMITTED_DEAL` and `AUTOMATED_DEAL` (1:1 inheritance)**             | Manual owner submissions and automated social media scrapes share core deal attributes (description, category, times, alcohol flag) but carry distinct source metadata (owner ID vs post ID, confidence score, scraped timestamp). Table inheritance avoids sparse tables filled with `NULL` columns while keeping common queries on `BASE_DEAL` clean. |
| **`venue_id` is stored on `BUSINESS_OWNER`**                                                   | An owner manages a specific bar or restaurant. Storing `venue_id` on `BUSINESS_OWNER` allows the Backend API Service to verify that an owner is authorized to submit deals for that specific venue during form validation.                                                                                                                              |
| **`VENUE` to `BASE_DEAL` is one-to-many**                                                      | Each deal belongs strictly to one physical venue, but a venue can host multiple active and historical deals over time.                                                                                                                                                                                                                                  |
| **`BASE_DEAL.alcohol` is indexed**                                                             | The Backend API Service filters out alcohol promotions for underage students on every search query. Indexing `alcohol` enables high-speed boolean lookups without triggering full table scans during peak evening traffic.                                                                                                                              |
| **Foreign keys (`venue_id`, `student_id`, `owner_id`, `base_deal_id`, `post_id`) are indexed** | Fetching student saved deals, venue listings, and parsed deal posts requires continuous table joins. Indexing every foreign key maintains O(log N) performance for join queries.                                                                                                                                                                        |
| **`AUTOMATED_DEAL.scraped_at` is indexed**                                                     | Scraped social media deals require frequent time checks to identify stale or outdated promotions. Indexing `scraped_at` allows rapid background cleanup routines and time-sorted deal feeds.                                                                                                                                                            |
